id: P006913
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:30:22.195584
source_metadata:
  id: bdr:W28953
  title: བོད་ཡིག་གི་དུས་གསུམ་རྣམ་གཞག
  author: ''
  volumes:
    7a89c703ee6946ad8386079743441287:
      image_group_id: I4945
      title: ''
      volume_number: 1
      total_pages: 70
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
